---

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ganglia-webfrontend
    - rrdtool
  tags:
    - ganglia_web_install
    - ganglia_web
    - install
    - ganglia

- name: configure
  file:
    src: /etc/ganglia-webfrontend/apache.conf
    path: /etc/apache2/sites-available/ganglia.conf
    state: link
  tags:
    - ganglia_web_configure
    - ganglia_web
    - configure
    - ganglia


- name: enable ganglia web interface
  command: a2ensite ganglia
  register: enable_ganglia
  changed_when: "'Enabling site' in enable_ganglia.stdout"
  tags:
    - ganglia_web_configure
    - ganglia_web
    - configure
    - ganglia


- name: reload apache
  service:
    name: apache2
    state: reloaded
  tags:
    - ganglia_web_service
    - ganglia_web
    - ganglia_service
    - ganglia
    - service
