---

- name: download
  get_url:
    url: "{{ spark_url }}"
    dest: "{{ ansible_env.PWD }}/{{ _spark_package_name }}"
    sha256sum: "{{ spark_sha256 }}"
  tags:
    - spark_install
    - spark
    - install

- name: extract
  unarchive:
    dest: "{{ spark_install_dest }}"
    src: "{{ ansible_env.PWD }}/{{ _spark_package_name }}"
    copy: no
    creates: "{{ spark_install_dest }}/{{ _spark_directory }}"
  tags:
    - spark_install
    - spark
    - install

- include: build.yml
  when: spark_package_type == 'src'

- name: symlink
  when: spark_create_link
  file:
    path: "{{ spark_install_dest }}/{{ spark_link_name }}"
    src: "{{ spark_install_dest }}/{{ _spark_directory }}"
    state: link
  tags:
    - spark_install
    - spark
    - install

- name: configure spark-env.sh
  lineinfile:
    dest: "{{ _spark_path_conf }}/spark-env.sh"
    line: "{{ item }}"
    create: yes
  with_items: "{{ spark_config_spark_env_sh + spark_config_spark_env_sh_extra }}"
  tags:
    - spark_configure
    - spark
    - configure

- name: add to profile.d
  lineinfile:
    dest: "/etc/profile.d/spark.sh"
    line: "export {{ item }}"
    create: yes
  with_items:
    - SPARK_HOME={{ spark_install_dest }}/{{ spark_link_name }}
    - PATH=$PATH:$SPARK_HOME/bin
  tags:
    - spark
    - spark_install
    - spark_profile_d
    - install
    - profile_d
