---

- name: ensure configuration directory exists
  file:
    path: "{{ hadoop_cfg_path }}"
    state: directory
  tags:
    - hadoop_configure
    - hadoop
    - configure


- name: clear configuration
  copy:
    src: empty-site.xml
    dest: "{{ hadoop_cfg_path }}/{{ item }}"
  with_items: "{{ clear_configs }}"
  notify: fix permissions
  tags: 
    - hadoop_configure
    - hadoop
    - configure


- name: configure core-site.xml
  lineinfile:
    dest: "{{ hadoop_cfg_path }}/core-site.xml"
    insertbefore: "</configuration>"
    line: "  <property>\n    <name>{{ item.key }}</name>\n    <value>{{ item.value }}</value>\n  </property>\n"
  with_dict: "{{ core_site }}"
  notify: fix permissions
  tags: 
    - hadoop_configure
    - hadoop
    - configure


- name: configure hdfs-site.xml
  lineinfile:
    dest: "{{ hadoop_cfg_path }}/hdfs-site.xml"
    insertbefore: "</configuration>"
    line: "  <property>\n    <name>{{ item.key }}</name>\n    <value>{{ item.value }}</value>\n  </property>\n"
  with_dict: "{{ hdfs_site }}"
  notify: fix permissions
  tags: 
    - hadoop_configure
    - hadoop
    - configure


- name: configure yarn-site.xml
  lineinfile:
    dest: "{{ hadoop_cfg_path }}/yarn-site.xml"
    insertbefore: "</configuration>"
    line: "  <property>\n    <name>{{ item.key }}</name>\n    <value>{{ item.value }}</value>\n  </property>\n"
  with_dict: "{{ yarn_site }}"
  notify: fix permissions
  tags: 
    - hadoop_configure
    - hadoop
    - configure


- name: configure mapred-site.xml
  lineinfile:
    dest: "{{ hadoop_cfg_path }}/mapred-site.xml"
    insertbefore: "</configuration>"
    line: "  <property>\n    <name>{{ item.key }}</name>\n    <value>{{ item.value }}</value>\n  </property>\n"
  with_dict: "{{ mapred_site }}"
  notify: fix permissions
  tags: 
    - hadoop_configure
    - hadoop
    - configure


  
