---

- name: install packages
  apt:
    name: gmetad
    state: present
  tags:
    - ganglia_metad_install
    - ganglia_metad
    - metad
    - install
    - ganglia

- name: configure
  template:
    src: gmetad.conf.j2
    dest: /etc/ganglia/gmetad.conf
  tags:
    - ganglia_metad_configure
    - ganglia_metad
    - metad
    - configure
    - ganglia

- name: restart gmetad
  service:
    name: gmetad
    state: restarted
  tags:
    - ganglia_metad_service
    - ganglia_metad
    - ganglia_service
    - ganglia
    - service
