---

- name: install java
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ java_packages }}"
  tags:
    - java_install
    - java
    - install

- name: add to profile.d
  lineinfile:
    dest: "/etc/profile.d/java.sh"
    line: "export {{ item }}"
    create: yes
  with_items:
    - JAVA_HOME=$(dirname $(dirname $(dirname $(update-alternatives --list java))))
  tags:
    - java
    - java_install
    - install
