---

spark_version: 1.6.0
spark_package_type: src
spark_hadoop_profile: hadoop-2.2
spark_url: "{{ _spark_url[spark_package_type][spark_version] }}"
spark_sha256: "{{ _spark_sha256[spark_package_type][spark_version] }}"
spark_install_dest: /opt
spark_create_link: yes
spark_link_name: spark

spark_config_local_ip: "{{ ansible_eth0.ipv4.address }}"
spark_config_spark_env_sh:
  - export SPARK_HOME={{ _spark_home }}
  - export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
  - export SPARK_LOCAL_IP={{ spark_config_local_ip }}

spark_config_spark_env_sh_extra: []

spark_build_with_yarn: yes
spark_build_hadoop_version: 2.2.0
spark_build_hadoop_profile: hadoop-2.2
spark_build_skip_tests: no
spark_build_clean: yes
spark_build_mvn_extra_opts: ""

_spark_build_mvn_opts_list:
  - "{{ '-Pyarn' if spark_build_with_yarn else '' }}"
  - "{{ '-P' + spark_build_hadoop_profile }}"
  - "{{ '-Dhadoop.version=' + spark_build_hadoop_version }}"
  - "{{ '-DskipTests' if spark_build_skip_tests else '' }}"
  - "{{ 'clean' if spark_build_clean else '' }}"
  - "{{ spark_build_mvn_extra_opts }}"
  - "package"

_spark_build_mvn_opts: "{{ _spark_build_mvn_opts_list | join(' ') }}"


_spark_package_name: "{{ spark_url | basename }}"
_spark_directory: "{{ _spark_package_name.rstrip('.tgz') }}"

_spark_sha256:
  src:
    1.6.0: 8a0a22cd126bdbc7fd90f20eb7a3b0508e726c062b31d901a6bf96646376830a
    1.5.1: 96cfd31ab5c07fe40dfca0475c7df888e2abf15126ff2a3c3af1facd02f1a848
    1.3.1: aea2384ec5694220d373b64f42d21b34e0df5aa50d15b1b6f6ce5edb5c4b4466
  bin:
    1.6.0: 439fe7793e0725492d3d36448adcd1db38f438dd1392bffd556b58bb9a3a2601
    1.5.1: 41ab59b28581b7952e3b0cfd8182980f033d2bf22d0f6a088ee6d120ddf24953
    1.3.1: a25aaf58cfb3c64e3c77bdf9dde1a61247846d60519dd28b18d60d162d19c79a



_spark_url:
  src:
    1.6.0: http://d3kbcqa49mib13.cloudfront.net/spark-1.6.0.tgz
    1.5.1: http://d3kbcqa49mib13.cloudfront.net/spark-1.5.1.tgz
    1.3.1: http://d3kbcqa49mib13.cloudfront.net/spark-1.3.1.tgz
  bin:
    1.6.0: http://d3kbcqa49mib13.cloudfront.net/spark-1.6.0-bin-hadoop2.6.tgz
    1.5.1: http://d3kbcqa49mib13.cloudfront.net/spark-1.5.1-bin-hadoop2.6.tgz
    1.3.1: http://d3kbcqa49mib13.cloudfront.net/spark-1.3.1-bin-hadoop2.6.tgz



_spark_home: "{{ spark_install_dest }}/{{ _spark_directory }}"
_spark_path_conf: "{{ _spark_home }}/conf"
