---

ganglia_gmon_conf_path: /etc/ganglia/gmond.conf

ganglia_defaults_gmon_port: 8649

ganglia_defaults_cluster_name: unspecified
ganglia_defaults_cluster_owner: unspecified
ganglia_defaults_cluster_latlong: unspecified
ganglia_defaults_cluster_url: unspecified

ganglia_cluster: {}

ganglia_udp_send_channels:
  - port: "{{ ganglia_defaults_gmon_port }}"

ganglia_udp_recv_channels:
  - port: "{{ ganglia_defaults_gmon_port }}"

ganglia_tcp_accept_channels:
  - port: "{{ ganglia_defaults_gmon_port }}"

# more complex example with ACLs list
#
#ganglia_udp_recv_channels:
#      - bind: "{{ ansible_default_ipv4.address }}"
#        port: "{{ ganglia_defaults_gmon_port }}"
#        acl:
#         - default: "deny"
#           access:
#            - ip: "192.168.1.0"
#              mask: 24
#              action: "allow"
#      - family: "inet6"
#        port: "{{ ganglia_defaults_gmon_port }}"
#        acl:
#         - default: "deny"
#           access:
#            - ip: "fe80::bbb:cccc:dddd:ffff"
#              mask: 128
#              action: "allow"
#
