---

- name: install packages
  apt:
    name: ganglia-monitor
    state: present
  tags:
    - ganglia_mond_install
    - ganglia_mond
    - install
    - ganglia


- name: configure
  template:
    src: gmond.conf.j2
    dest: "{{ ganglia_gmon_conf_path }}"
    backup: yes
  tags:
    - ganglia_mond_configure
    - ganglia_mond
    - configure
    - ganglia

- name: restart gmond
  service:
    name: ganglia-monitor
    state: restarted
  tags:
    - ganglia_mond_service
    - ganglia_mond
    - ganglia_service
    - ganglia
    - service
